name: Lint All
description: Lint all files in the repository

runs:
  using: composite
  steps:
    - name: Markdownlint CLi Action
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: "**/*.md"
        config: .markdownlint.jsonc

    - name: Prettier Action
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: --config .prettierrc --check .
        dry: true
