# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL: "https://hudsonmcnamara.com"
defaultContentLanguage: "en"

# pluralizeListTitles: true # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT: true
summaryLength: 0

buildDrafts: false
buildFuture: true

enableEmoji: true

enableGitInfo: true

googleAnalytics: "G-G330H1ZLPY"

pagination:
  pagerSize: 100

imaging:
  anchor: Center

taxonomies:
  tag: tags
  series: series

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON

related:
  threshold: 0
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: series
      weight: 50
    - name: date
      weight: 10
    - applyFilter: false
      name: fragmentrefs
      type: fragments
      weight: 10

minify:
  tdewolff:
    html:
      keepWhitespace: true # strips out spaces between some icons/text if false
