disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Hudson McNamara"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Hudson McNamara"
email = "hudson@ziroau.com"
image = "img/author.png"
imageQuality = 96
headline = "IT & Automation"
bio = "System Engineer"
links = [
  { email = "mailto:hudson@ziroau.com" },
  { github = "https://github.com/hudsonm62" },
  { linkedin = "https://linkedin.com/in/hudsonmcnamara" },
  { camera-solid = "https://unsplash.com/@ziroau" }
  #{ mastodon = "https://zynk.quest/@hudson" }
  #{ bluesky = "https://bsky.app/profile/hudsonmcnamara.com" }
  #{ instagram = "https://instagram.com/ziroau" },
  #{ camera-solid = "https://unsplash.com/@ziroau" }
  #     { steam = "https://steamcommunity.com/id/username" }
  #     { link = "https://link-to-some-website.com/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { google = "https://www.google.com/" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { itch-io = "https://username.itch.io" },
  #     { keybase = "https://keybase.io/username" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  #     { orcid = "https://orcid.org/userid" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  #     { spotify = "https://open.spotify.com/user/userid" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { telegram = "https://t.me/username" },
  #     { threads = "https://www.threads.net/@username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/username" },
  #     { x-twitter = "https://twitter.com/username" },
  #     { whatsapp = "https://wa.me/phone-number" },
  #     { youtube = "https://youtube.com/username" },
  #     { ko-fi = "https://ko-fi.com/username" },
  #     { codeberg = "https://codeberg.org/username"},
]
