name: 🧪 CI

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  HUGO_GOCACHE: /tmp/hugo_cache_runner
  NODE_VERSION: 24.x
  HUGO_VERSION: 0.163.3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout Repo
        id: checkout
        uses: actions/checkout@v7

      - name: ✨ Markdownlint CLi2 Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: "**/*.md"
          config: .markdownlint-cli2.jsonc

      - name: ✨ Prettier Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --config .prettierrc --check .
          dry: true

  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      # Build Site
      - name: ⚙️ Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Cache Hugo Modules
        uses: actions/cache@v6
        with:
          path: ${{ env.HUGO_GOCACHE }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: 🔨 Build Hugo Site
        run: npm run build

      - name: 🌌 Get Run Metadata
        id: setup-meta
        uses: ./.github/actions/get-metadata

      - name: ⬆ Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: hugosite-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: public
          compression-level: 9
